Working on the bootstrapper

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,9 +3,6 @@
 # bootstrap the dotfiles setup
 
 # TODO
-# 1. CD to parent directory of current script
-# 2. Source core.sh
-# 3. Remove duplicate code (ref. core)
 # 4. Move to msg_
 # 5. Deal with symlinking non dotfiles
 
@@ -14,56 +11,15 @@ set -o pipefail	  # fail entire pipeline
 set -o nounset	  # exit on any attempt to use uninitialized variables
 set -o errexit	  # exit the script if any statement returns non-true
 
+# Rather than using relative paths just cd into the script directory
+# This works better for linting as well
 _SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
-_ERR_PIPE="$(mktemp -u)"
-_DEBUG=true
-_TRACE=true
+cd "$_SCRIPT_PATH" || exit 1
 
-# Wire up temporary named pipe to store stderr for use in ERR trap
-mkfifo "$_ERR_PIPE"
-
-# Redirect file descriptor 3 to stdout
-# Tee stdout to named pipe, then get stderr to fd 3 
-exec 3>&1
-exec > >(tee "$_ERR_PIPE") 2>&1 1>&3
-
-# Wire up ERR and EXIT traps
-trap 'trap_err $LINENO $?' ERR
-trap 'trap_exit' EXIT
-
-function trap_err()
-{
-	local message
-	local code
-
-	message="$(head -n1 < "$_ERR_PIPE")"
-	code="${2:-1}"
-	echo "${code}>Error on line $1: $message"
-	exit "$code"
-}
-
-function trap_exit()
-{
-	# Clean up the named pipe
-	rm "$_ERR_PIPE"
-	exec 3>&-
-}
-
-function DEBUG()
-{
-	if $_DEBUG; then
-		echo "[DEBUG] $*"
-	elif $_TRACE; then
-		# Run in subshell so that we dont need to use set +x
-		# ( which would be sent to stdout by the set -x
-		(
-			set -x
-			eval "$*"
-		)
-	else
-		eval "$*"
-	fi 
-}
+# Bring in the core library and enable global error handler
+# No futher need to check return codes after this point ...
+source ./lib/core.sh || exit 1
+USE_GLOBAL_ERROR_HANDLER
 
 function path_exists() 
 {
